/************************************
 * Entity Type Management 
 ************************************/

CREATE TABLE IF NOT EXISTS entity_type (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type_name VARCHAR(255) NOT NULL UNIQUE,
    default_config JSONB
);

comment on table entity_type is 'Table to define different types of entities in the system';
comment on column entity_type.entity_type_name is 'System human friendly name of the entity type';
comment on column entity_type.description is 'Description of the entity type';
comment on column entity_type.default_config is 'Default configuration for the entity type in JSON format';

/************************************
 * Entity Management 
 ************************************/

CREATE TABLE IF NOT EXISTS entity (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name VARCHAR(255) NOT NULL UNIQUE,
    --id_entity_type INT NOT NULL REFERENCES entity_type(id),
    extra_config JSONB
);

comment on table entity is 'Table to store entities in the system';
comment on column entity.entity_name is 'System human friendly name of the entity';
comment on column entity.uuidv4_entity_type is 'UUID of the entity type from entity_type table';
comment on column entity.text_id is 'UUID of the text from texts table, used for translations';
comment on column entity.extra_config is 'Additional configuration for the entity in JSON format, can be combined with jsonb_concat with the default_config from entity_type';

