/*
 * Entity Management System
 * This script creates tables and functions to manage entities in a manufacturing system.
 * 
 */

-- Will drop everything in the schema
DROP SCHEMA public CASCADE;
-- Recreate the schema
CREATE SCHEMA public;

/************************************
 * Extensions
 ************************************/
-- Enable the uuid-ossp extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- Enable the ltree extension for hierarchical data management
CREATE EXTENSION IF NOT EXISTS ltree;
-- Enable the pgcrypto extension for cryptographic functions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

/************************************
 * File includes
 ************************************/

-- CREATE TABLE IF NOT EXISTS entity_type (
--     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     entity_type VARCHAR(255) NOT NULL UNIQUE,
--     config JSONB
-- );

-- insert into entity_type (entity_name, config) values
-- ('W', '{}'),('M', '{}'), ('P', '{}');


-- CREATE TABLE IF NOT EXISTS entity (
--     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     entity_name VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
--     entity_type VARCHAR(255) NOT NULL REFERENCES entity_type(entity_type),
--     extra_config JSONB
-- );

-- insert into entity (entity_name, extra_config) values
-- ('WC01', '{}'), ('WC02', '{}'), ('WC03', '{}'), ('WC04', '{}'), ('WC05', '{}'),
-- ('WC06', '{}'), ('WC07', '{}'), ('WC08', '{}'), ('WC09', '{}'), ('WC10', '{}'),
-- ('WC11', '{}'), ('WC12', '{}'), ('WC13', '{}'), ('WC14', '{}'), ('WC15', '{}'),
-- ('WC16', '{}'), ('WC17', '{}'), ('WC18', '{}'), ('WC19', '{}'), ('WC20', '{}');

-- insert into entity (entity_name, extra_config) values
-- ('M01', '{}'), ('M02', '{}'), ('M03', '{}'), ('M04', '{}'), ('M05', '{}'),
-- ('M06', '{}'), ('M07', '{}'), ('M08', '{}'), ('M09', '{}'), ('M10', '{}'),
-- ('M11', '{}'), ('M12', '{}'), ('M13', '{}'), ('M14', '{}'), ('M15', '{}'),
-- ('M16', '{}'), ('M17', '{}'), ('M18', '{}'), ('M19', '{}'), ('M20', '{}');

-- insert into entity (entity_name, extra_config) values
-- ('P01', '{}'), ('P02', '{}'), ('P03', '{}'), ('P04', '{}'), ('P05', '{}'),
-- ('P06', '{}'), ('P07', '{}'), ('P08', '{}'), ('P09', '{}'), ('P10', '{}'),
-- ('P11', '{}'), ('P12', '{}'), ('P13', '{}'), ('P14', '{}'), ('P15', '{}'),
-- ('P16', '{}'), ('P17', '{}'), ('P18', '{}'), ('P19', '{}'), ('P20', '{}');

-- create table IF NOT EXISTS entity_relations (
--     --id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     parent VARCHAR(255) NOT NULL REFERENCES entity(entity_name) ,
--     child VARCHAR(255) NOT NULL REFERENCES entity(entity_name) ,
--     relation_type VARCHAR(50) NOT NULL
-- );

create type IF NOT EXISTS entity_relation_type AS jsonb (
    parent VARCHAR(255) NOT NULL,
    child VARCHAR(255) NOT NULL,
    relation_type VARCHAR(50) NOT NULL
);